"""category unique_together for name, user_id, kind

Revision ID: 4a296b8280c1
Revises: 2efdf6e3fe59
Create Date: 2025-08-26 21:11:37.443937

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a296b8280c1"
down_revision: Union[str, Sequence[str], None] = "2efdf6e3fe59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq__category__user_name_kind",
        "categories",
        ["user_id", "name", "kind"],
    )
    op.create_index(
        "ux__category__user_kind_lower_name",
        "categories",
        ["user_id", "kind", sa.literal_column("lower(name)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ux__category__user_kind_lower_name", table_name="categories")
    op.drop_constraint("uq__category__user_name_kind", "categories", type_="unique")
    # ### end Alembic commands ###
