"""accounts unique_together for name and user_id

Revision ID: 2efdf6e3fe59
Revises: 6e2dd4a47efa
Create Date: 2025-08-25 22:22:08.017718

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2efdf6e3fe59"
down_revision: Union[str, Sequence[str], None] = "6e2dd4a47efa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq__account__user_name", "accounts", ["user_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq__account__user_name", "accounts", type_="unique")
    # ### end Alembic commands ###
